---
management:            
  endpoints:
    enabled-by-default: false

server:
  port: 3000
          
spring:
  datasource:
    driverClassName: com.vertica.jdbc.Driver
    url: jdbc:vertica://192.168.1.35:5433/VMart?loginTimeout=35
    username: dbadmin
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true